### ISSUE TITLE
Lack of failsafe for an empty header

### ISSUE THREAD

**Issue by SoftBrilliant** [nnguyen259/KuroTools#23]
If a header is empty (meaning it has an entry count of 0), the program will give out a key error 1 as it tries to recompile completely garbage data.
Kuro 2's t_quest features 2 empty headers (QuestSubText and RecruitmentMember) and there's no real fix on my end aside from inconveniencing the user with the equivalent of disk swapping but for files so that the program doesn't try to recompile nothing.

Error message:

[https://imgur.com/KsTwpZa](url)

Removing the presence of the empty headers from the file entirely also allows it to compile.

**Comment by TwnKey** [comment]
Should be fixed now https://github.com/nnguyen259/KuroTools/commit/5737a2eb3f757a1db8e7bce5e53d75e5cc470215
