### ISSUE TITLE
Problem decompiling tbl files in Kuro 2

### ISSUE THREAD

**Issue by casrup** [nnguyen259/KuroTools#27]
Issue encountered on CLE PC version of Kuro 2.
I may be missing something, but after running tbl2json.py on a .tbl file and replacing the original file in the /f/table folder, launching the game opens an error box saying (t_name.tbl used in this example):

Invalid file format.
kr/f/t_name.tbl
 expect: CR
 target: UN
 size: 416375

The size parameter seems to change depending on the file, and the box pops up twice, and also depending on the file the game fails to launch. Again, the only thing I've done to the file at this point is decompile to json format, I haven't made changes to it or recompiled the json file back, it's still the original file dragged back into the folder.

**Comment by TwnKey** [comment]
@SoftBrilliant @Shingentsu I'm guessing the file is not compressed/encrypted (which is a requirement for Kuro 2 to read it)

**Comment by casrup** [comment]
Wow that's embarrassing, I completely missed that on the readme, apologies for that. Had some problems getting compressing to work, but during troubleshooting it sorted itself out and now it works perfectly, thanks!
